# Generated by Django 5.0.2 on 2024-02-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geeksmodel',
            name='ready',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
